version: '2'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      AUTH: "no"
      USER: root
      PASS: root
  node:
    image: node
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - "./src:/var/www"
      - "./node_modules:/var/www/node_modules"
    working_dir: /var/www/         ## uses work dir /app
    entrypoint: node server.js   ## starts application
